package com.yourname.oracleapp.ui;

import com.yourname.oracleapp.ui.Crud;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.*;
import java.util.*;
import java.util.List;
import java.sql.Connection;


public class CrudPanel extends JPanel {

    private Crud crud;
    private Connection conn;

    private JComboBox<String> tableSelector;
    private JButton loadBtn, insertBtn, updateBtn, deleteBtn, backBtn;
    private JLabel statusLabel;

    private JTable dataTable;
    private DefaultTableModel tableModel;

    private JPanel formPanel;
    private Map<String, JTextField> fieldMap = new LinkedHashMap<>();
    private String primaryKey;
    private boolean autoGeneratedPK = false;

    private Runnable onBack;

    private final Color PRIMARY_BG = new Color(28, 48, 74);
    private final Color SECONDARY_BG = new Color(43, 74, 111);
    private final Color FONT_LIGHT = new Color(217, 217, 217);
    private final Color FIELD_BG = new Color(35, 60, 90);
    private final Color TABLE_CELL_BG = new Color(20, 35, 55);
    private final Color GRID_COLOR_NEW = new Color(60, 90, 120);
    private final Color BTN_HOVER_NEW = new Color(60, 100, 145);
    private final Color SELECTION_BG = new Color(55, 85, 125);

    public CrudPanel(Connection conn, Runnable onBack) {
        this.conn = conn;
        this.crud = new Crud(conn);
        this.onBack = onBack;

        try { conn.setAutoCommit(true); } catch (Exception e) {}

        setLayout(new BorderLayout(10, 10));
        setBackground(PRIMARY_BG);

        JPanel topPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        topPanel.setBackground(SECONDARY_BG);
        JLabel tableLabel = new JLabel("Select Table:");
        tableLabel.setForeground(FONT_LIGHT);
        tableSelector = new JComboBox<>(crud.getTables());
        styleComboBox(tableSelector);
        loadBtn = styledButton("Load Table");
        loadBtn.addActionListener(e -> loadTable());
        topPanel.add(tableLabel);
        topPanel.add(tableSelector);
        topPanel.add(loadBtn);
        add(topPanel, BorderLayout.NORTH);

        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT);
        splitPane.setBackground(PRIMARY_BG);
        splitPane.setDividerSize(3);
        splitPane.setResizeWeight(0.6);

        tableModel = new DefaultTableModel();
        dataTable = new JTable(tableModel);
        styleTable(dataTable);
        JScrollPane tableScroll = new JScrollPane(dataTable);
        styleScrollPane(tableScroll);
        splitPane.setLeftComponent(tableScroll);

        formPanel = new JPanel(new GridBagLayout());
        formPanel.setBackground(SECONDARY_BG);
        JScrollPane formScroll = new JScrollPane(formPanel);
        styleScrollPane(formScroll);
        splitPane.setRightComponent(formScroll);

        add(splitPane, BorderLayout.CENTER);

        JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        bottomPanel.setBackground(SECONDARY_BG);
        insertBtn = styledButton("Insert");
        updateBtn = styledButton("Update");
        deleteBtn = styledButton("Delete");
        backBtn = styledButton("Back");
        statusLabel = new JLabel("Ready");
        statusLabel.setForeground(FONT_LIGHT);
        bottomPanel.add(insertBtn);
        bottomPanel.add(updateBtn);
        bottomPanel.add(deleteBtn);
        bottomPanel.add(backBtn);
        bottomPanel.add(statusLabel);
        add(bottomPanel, BorderLayout.SOUTH);

        insertBtn.addActionListener(e -> handleInsert());
        updateBtn.addActionListener(e -> handleUpdate());
        deleteBtn.addActionListener(e -> handleDelete());
        backBtn.addActionListener(e -> onBack.run());

        dataTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && dataTable.getSelectedRow() != -1) {
                int row = dataTable.getSelectedRow();
                for (int col = 0; col < dataTable.getColumnCount(); col++) {
                    String colName = dataTable.getColumnName(col);
                    Object val = dataTable.getValueAt(row, col);
                    if (fieldMap.containsKey(colName)) {
                        fieldMap.get(colName).setText(val != null ? val.toString() : "");
                    }
                }
            }
        });
    }

    private void loadTable() {
        String table = (String) tableSelector.getSelectedItem();
        if (table == null) return;

        List<Object[]> rows = crud.loadTableData(table);

        tableModel.setRowCount(0);
        tableModel.setColumnCount(0);

        List<Map<String,String>> cols = crud.getColumns(table);
        for (Map<String,String> c : cols) {
            tableModel.addColumn(c.get("name"));
        }

        for (Object[] r : rows) {
            tableModel.addRow(r);
        }
        statusLabel.setForeground(FONT_LIGHT);
        statusLabel.setText("Table loaded: " + table);


        buildForm(table);
    }

    private void buildForm(String table) {
        formPanel.removeAll();
        fieldMap.clear();

        List<Map<String, String>> cols = crud.getColumns(table);
        primaryKey = crud.getPrimaryKey(table);

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5,5,5,5);
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        int row = 0;
        for (Map<String, String> c : cols) {
            String name = c.get("name");
            String type = c.get("type");
            JLabel label = new JLabel(name + " (" + type + "):");
            styleLabel(label);
            JTextField tf = new JTextField(15);
            styleField(tf);

            gbc.gridx = 0; gbc.gridy = row;
            formPanel.add(label, gbc);
            gbc.gridx = 1;
            formPanel.add(tf, gbc);

            fieldMap.put(name, tf);
            row++;
        }

        formPanel.revalidate();
        formPanel.repaint();
        statusLabel.setForeground(FONT_LIGHT);
        statusLabel.setText("Form ready: " + table);
    }

    private void handleInsert() {
        String table = (String) tableSelector.getSelectedItem();
        if (table == null) return;
        Map<String, String> data = new LinkedHashMap<>();
        for (String col : fieldMap.keySet()) {
            data.put(col, fieldMap.get(col).getText().trim());
        }
        boolean ok = crud.insert(table, data, autoGeneratedPK, primaryKey);
        if (ok) {
            statusLabel.setForeground(FONT_LIGHT);
            statusLabel.setText("Inserted successfully.");
            loadTable();
        } else {
            statusLabel.setForeground(Color.RED);
            statusLabel.setText("Insert failed.");
        }
    }

    private void handleUpdate() {
        String table = (String) tableSelector.getSelectedItem();
        if (table == null || primaryKey == null) return;
        String pkVal = fieldMap.get(primaryKey).getText().trim();
        if (pkVal.isEmpty()) {
            statusLabel.setForeground(Color.RED);
            statusLabel.setText("Primary key required.");
            return;
        }
        Map<String, String> data = new LinkedHashMap<>();
        for (String col : fieldMap.keySet()) {
            data.put(col, fieldMap.get(col).getText().trim());
        }
        boolean ok = crud.update(table, data, primaryKey);
        if (ok) {
            statusLabel.setForeground(FONT_LIGHT);
            statusLabel.setText("Updated successfully.");
            loadTable();
        } else {
            statusLabel.setForeground(Color.RED);
            statusLabel.setText("Update failed.");
        }
    }

    private void handleDelete() {
        String table = (String) tableSelector.getSelectedItem();
        if (table == null || primaryKey == null) return;
        String pkVal = fieldMap.get(primaryKey).getText().trim();
        if (pkVal.isEmpty()) {
            statusLabel.setForeground(Color.RED);
            statusLabel.setText("Primary key required.");
            return;
        }
        boolean ok = crud.delete(table, primaryKey, pkVal);
        if (ok) {
            statusLabel.setForeground(FONT_LIGHT);
            statusLabel.setText("Deleted successfully.");
            loadTable();
        } else {
            statusLabel.setForeground(Color.RED);
            statusLabel.setText("Delete failed.");
        }
    }

    private JButton styledButton(String text) {
        JButton b = new JButton(text);
        b.setBackground(SECONDARY_BG);
        b.setForeground(FONT_LIGHT);
        b.setBorderPainted(false);
        b.setFocusPainted(false);
        b.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(GRID_COLOR_NEW, 1),
                BorderFactory.createEmptyBorder(5, 10, 5, 10)
        ));
        b.setPreferredSize(new Dimension(100, 35));
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) { b.setBackground(BTN_HOVER_NEW); }
            public void mouseExited(java.awt.event.MouseEvent evt) { b.setBackground(SECONDARY_BG); }
        });
        return b;
    }

    private void styleField(JTextField f) {
        f.setBackground(FIELD_BG);
        f.setForeground(FONT_LIGHT);
        f.setCaretColor(FONT_LIGHT);
        f.setBorder(BorderFactory.createLineBorder(GRID_COLOR_NEW));
    }

    private void styleLabel(JLabel l) { l.setForeground(FONT_LIGHT); }

    private void styleComboBox(JComboBox<String> c) {
        c.setBackground(FIELD_BG);
        c.setForeground(FONT_LIGHT);
        c.setBorder(BorderFactory.createLineBorder(GRID_COLOR_NEW));
    }

    private void styleScrollPane(JScrollPane sp) {
        sp.getViewport().setBackground(PRIMARY_BG);
        sp.setBorder(BorderFactory.createLineBorder(GRID_COLOR_NEW));
    }

    private void styleTable(JTable t) {
        t.setBackground(TABLE_CELL_BG);
        t.setForeground(FONT_LIGHT);
        t.setGridColor(GRID_COLOR_NEW);
        t.setSelectionBackground(SELECTION_BG);
        t.setSelectionForeground(Color.WHITE);

        t.getTableHeader().setBackground(SECONDARY_BG);
        t.getTableHeader().setForeground(FONT_LIGHT);
        t.getTableHeader().setOpaque(true);

        DefaultTableCellRenderer hdr = new DefaultTableCellRenderer();
        hdr.setBackground(SECONDARY_BG);
        hdr.setForeground(FONT_LIGHT);
        hdr.setHorizontalAlignment(JLabel.CENTER);
        t.getTableHeader().setDefaultRenderer(hdr);
    }
}